[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# Nighlty options
[nightly.build]
rustflags = ["-Z", "threads=8"]

[nightly.target.x86_64-unknown-linux-gnu.unstable]
codegen-backend = true

[nightly.target.x86_64-unknown-linux-gnu.profile.dev]
codegen-backend = "cranelift"